# Generated by Django 4.0.3 on 2022-04-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('d_or_c', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('m_no', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('paid', models.CharField(default='Not paid', max_length=10)),
                ('date_of_transaction', models.DateField(default='NA')),
            ],
        ),
        migrations.DeleteModel(
            name='AccountManagement',
        ),
    ]
