# Generated by Django 4.0.3 on 2022-04-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_data_date_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_data',
            name='paid',
            field=models.CharField(default='Not paid', max_length=10, null=True),
        ),
    ]
